runtime: python39

handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /assets
    static_dir: assets

  - url: /dashboard
    static_files: dashboard.html
    upload: dashboard.html

  - url: /settings
    static_files: settings.html
    upload: settings.html

  - url: /
    static_files: index.html
    upload: index.html

  - url: /.*
    static_files: index.html
    upload: index.html
